Importing the necessary libraries for webscraping and map building.

In [27]:
import pandas as pd
import numpy as np
import plotly.express as px
import selenium
import requests
from bs4 import BeautifulSoup
import re
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time

In [28]:
city_data = pd.read_csv('city_data_cleaned.csv')
city_data_coords = city_data.copy()
city_data_coords['Latitude'] = np.nan
city_data_coords['Longitude'] = np.nan

In [ ]:
wikipedia_url = "https://en.wikipedia.org/wiki/Main_Page"


def get_city_coordinates(city_name):
    """
    Starts on the Wikipedia main page and searches for the given city name.

    Parameters:
    city_name (str): The name of the city to search for.

    Returns:
    The city page URL.
    """
    # set up the Selenium WebDriver (make sure to have the appropriate driver installed)
    options = webdriver.ChromeOptions()
    # options.add_argument("--headless")  # Run in headless mode
    driver = webdriver.Chrome(options=options)
    driver.maximize_window()

    try:
        # navigate to Wikipedia main page
        driver.get(wikipedia_url)

        # find the search input box and enter the city name
        search_input = WebDriverWait(driver, 15).until(EC.element_to_be_clickable((By.ID, "searchInput")))
        search_input.send_keys(city_name)
        search_input.send_keys(Keys.RETURN)

        # wait for the page to load and get the current URL
        WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, "firstHeading")))
        city_latitude = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.CLASS_NAME, "latitude")))
        city_longitude = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.CLASS_NAME, "longitude")))

        return (city_latitude.text, city_longitude.text)
    
    finally:
        driver.quit()


def fill_dataset_coords(df):
    """
    Fills the dataset with latitude and longitude coordinates for each city.
    Parameters:
    df (DataFrame): The DataFrame containing city data.
    Returns:
    The updated DataFrame with latitude and longitude columns filled.
    """
    
    
    for city in df['City']:
        try: # attempt to get coordinates using "City, Country" format first
            df.loc[df['City'] == city, ['Latitude', 'Longitude']] = get_city_coordinates(f"{city}, {df.loc[city_data_coords['City'] == city, 'Country'].values[0]}")
        except Exception: # if that fails, try just the city name
            df.loc[df['City'] == city, ['Latitude', 'Longitude']] = get_city_coordinates(city)
    
    return df

# # filling the dataset with coordinates
# fill_dataset_coords(city_data_coords)
# fill_dataset_coords(city_data_coords[city_data_coords['City'] == 'Rotterdam'])
# display(city_data_coords[['Latitude', 'Longitude']])
# city_data_coords.to_csv('city_data_with_coords.csv', index=False)

# # Iterative Map Building and visualization

# city_data_coords[['Latitude']] = city_data_coords[['Latitude']].replace('N','')
# city_data_coords[['Longitude']] = city_data_coords[['Longitude']].replace('E','')
# display(city_data_coords[['Latitude', 'Longitude']])

# map_df = city_data_coords.dropna(subset=['Latitude', 'Longitude'])

# fig_map = px.scatter_map(
#         map_df,
#         lat="Latitude",
#         lon="Longitude",
#         hover_name="City",
#         hover_data={
#             "Latitude": False, "Longitude": False,
#             "Country": True,
#             "Population": ':,.0f', 
#             "Average Monthly Salary": ':,.0f €', 
#             "Average Cost of Living": ':,.0f €'  
#         },
#         color="Average Monthly Salary", 
#         size="Population",              
#         color_continuous_scale="Viridis",
#         zoom=3, 
#         height=700,
#         title="Iterative Map of Cities with Population, Average Monthly Salary, and Cost of Living"
#     )

# fig_map.update_layout(mapbox_style="open-street-map")
# fig_map.update_layout(margin={"r":0,"t":40,"l":0,"b":0})
# fig_map.show()

    Latitude  Longitude
0        NaN        NaN
1        NaN        NaN
2        NaN        NaN
3        NaN        NaN
4        NaN        NaN
..       ...        ...
79       NaN        NaN
80       NaN        NaN
81       NaN        NaN
82       NaN        NaN
83       NaN        NaN

[84 rows x 2 columns]

    Latitude  Longitude
0        NaN        NaN
1        NaN        NaN
2        NaN        NaN
3        NaN        NaN
4        NaN        NaN
..       ...        ...
79       NaN        NaN
80       NaN        NaN
81       NaN        NaN
82       NaN        NaN
83       NaN        NaN

[84 rows x 2 columns]